image: docker.nix-community.org/nixpkgs/cachix-flakes

build:
  variables:
    CACHIX_CACHE_NAME: vtos
  before_script:
    - cachix use "$CACHIX_CACHE_NAME"
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix flake check --extra-experimental-features nix-command --extra-experimental-features flakes --all-systems
