apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/name: prometheus
configMapGenerator:
  - name: prometheus-config
    files:
      - config/prometheus.yml
resources:
  - ./cluster-role.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./node-exporter
