apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-cert
spec:
  secretName: nginx-cert

  dnsNames:
    - nginx.homelab.v-thomas.com

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
