apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./secret.yaml
  - ./cluster-issuers.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml

# secretGenerator:
#   - name: letsencrypt-email
#     literals:
#       - email=$(EMAIL)
