apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
spec:
  secretName: traefik-cert
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: ingress
      app.kubernetes.io/name: traefik
      app.kubernetes.io/component: certificate

  dnsNames:
    - traefik.homelab.v-thomas.com

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
