api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  kubernetesCRD:
    nativeLBByDefault: true
  file:
    filename: /etc/traefik/dynamic.yaml
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true






