apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./core/cert-manager
  - ./core/metallb
  - ./core/traefik
  - ./core/grafana
  - ./core/prometheus
  # - ./services/cloudflared
  - ./apps/nginx
  - ./apps/rancher
