apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-cert
spec:
  secretName: rancher-cert
  dnsNames:
    - rancher.homelab.v-thomas.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
