apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
spec:
  secretName: grafana-cert
  secretTemplate:
    labels:
      app.kubernetes.io/part-of: monitoring
      app.kubernetes.io/name: grafana
      app.kubernetes.io/component: certificate
  dnsNames:
    - grafana.homelab.v-thomas.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
