apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingressroutes.yaml
  - certificate.yaml
namePrefix: nginx-
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: nginx
